site:
  title: Cecil
  baseline: An easy and lightweight static website generator!
  baseurl: https://cecil.app/
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  language: en
